apiVersion: v1
kind: ConfigMap
metadata:
  name: telco-data-plane-config  # Flux is getting this
  namespace: default
  labels:
    app: upf-core
    managed-by: flux
data:
  upf.yaml: |
    logger:
      path:
        file: /opt/open5gs/var/log/open5gs/upf.log

    # N4 Interface
    # UPF listens for PFCP session rules from the SMF on UDP 8805
    upf:
      pfcp:
        server:
        - dev: eth0

    # N3 INTERFACE
    # gtp-u traffic - Port 2152
      gtpu:
        server:
          - dev: n3


    # N6 Forwarding is taken care of by Linux
      session:
        - subnet: 10.45.0.0/16
          gateway: 10.45.0.1
          dnn: internet

      metrics:
        server:
          - dev: eth0
            port: 9090
