apiVersion: v1
kind: Service
metadata:
  name: open5gs-upf-pfcp
  namespace: default
spec:
  selector:
    app: upf-core
  ports:
    - name: pfcp
      protocol: UDP
      port: 8805
      targetPort: 8805
  type: ClusterIP