# apps/upf/deployment.yaml (Part 1)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: upf-core-engine
  namespace: default
  labels:
    app: upf-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upf-core
  template:
    metadata:
      labels:
        app: upf-core
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
          { "name": "telco-n3-plane", "interface": "n3" },  
          { "name": "telco-n6-plane", "interface": "n6" }
        ]'
    spec:
      # securityContext:
      #   privileged: true
        # sysctls:
        #   - name: net.ipv4.ip_forward
        #     value: "1"
      initContainers:
        - name: configure-routes
          image: alpine:3.18
          command:
            - /bin/sh
            - -c
            - |
              # Install iptables utility quickly before running commands
              apk add --no-cache iptables
              
              # 1. Create a custom routing table (Table 2) inside the container
              ip rule add from 10.45.0.0/16 lookup 2
              
              # 2. Add the default internet gateway route matching your 10.0.2.0/24 subnet
              ip route add default via 10.0.2.1 dev n6 table 2
              
              # 3. Enabled: Perforrms Source NAT so AWS returns traffic properly
              iptables -t nat -A POSTROUTING -o n6 -j MASQUERADE
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
      volumes:
        - name: upf-config-volume
          configMap:
            defaultMode: 420
            name: telco-data-plane-config
            items:
              - key: upf.yaml
                path: upf.yaml
        - name: dev-net-tun
          hostPath:
            path: /dev/net/tun
            type: CharDevice
      containers:
        - name: upf-container
          image: gradiant/open5gs:2.7.2
          securityContext:
            privileged: true
            runAsUser: 0
          args:
            - /opt/open5gs/bin/open5gs-upfd 
          #image: 468402787427.dkr.ecr.us-east-1.amazonaws.com/upf_worker:latest@sha256 # {"$imagepolicy": "flux-system:seshat-api-latest"}
          # imagePullPolicy: Always
          # securityContext:         
          #   allowPrivilegeEscalation: true # Hardened: Prevents exploitation escalation loops
          #   privileged: false
          #   capabilities:
          #     drop:
          #       - ALL                   # 1. Strips away all 40 standard root access privileges
          #     add:
          #       - NET_ADMIN
          #       - SYS_ADMIN
          volumeMounts:
            - name: upf-config-volume
              mountPath: /etc/open5gs/
            - name: dev-net-tun
              mountPath: /dev/net/tun
          ports:
            - containerPort: 2123 # N4 Control Plane Port
              name: n4-port
            - containerPort: 2152 # N3 User Plane Port
              name: n3-port