apiVersion: apps/v1
kind: Deployment
metadata:
  name: n6-gateway
  namespace: default

spec:
  replicas: 1

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app: n6-gateway

  template:
    metadata:
      labels:
        app: n6-gateway
      annotations:
        k8s.v1.cni.cncf.io/networks: |-
          [{
            "name": "telco-n6-plane",
            "interface": "n6",
            "ips": ["192.168.200.151/24"]
          }]

    spec:
      nodeName: ip-10-0-3-97.ec2.internal
      containers:
        - name: gateway
          image: alpine:3.20

          securityContext:
            capabilities:
              add:
                - NET_ADMIN

          command:
            - /bin/sh
            - -c

          args:
            - |
              apk add --no-cache iptables
              sysctl -w net.ipv4.ip_forward=1
              iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
              iptables -A FORWARD -i n6 -o eth0 -j ACCEPT
              iptables -A FORWARD -i eth0 -o n6 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
              sleep infinity