apiVersion: apps/v1
kind: Deployment
metadata:
  name: seshat-vdu-deployment
  namespace: default
  labels:
    app: seshat-vdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seshat-vdu
  template:
    metadata:
      labels:
        app: seshat-vdu
      annotations:
        k8s.v1.cni.cncf.io/networks: telco-data-plane
    spec:
      serviceAccountName: seshat-vdu-sa
      containers:
        - name: seshat-vdu
          #  Total Bullshit!
          image: 468402787427.dkr.ecr.us-east-1.amazonaws.com/seshat_api:latest@sha256:cd807153b211eb031dc59c9a79b56fdd296e2c26c7409066f5bee5cd7289400d # {"$imagepolicy": "flux-system:seshat-api-latest"}  
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
