apiVersion: apps/v1
kind: Deployment
metadata:
  name: seshat-vdu-deployment
  namespace: default
  labels:
    app: seshat-vdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seshat-vdu
  template:
    metadata:
      labels:
        app: seshat-vdu
      annotations:
        k8s.v1.cni.cncf.io/networks: telco-data-plane
    spec:
      serviceAccountName: seshat-vdu-sa
      containers:
        - name: seshat-vdu
          #  Total Bullshit!
          image: 468402787427.dkr.ecr.us-east-1.amazonaws.com/seshat_api:latest@sha256:5055d920fde7f44940fce58744f648776b254bb20073ddf8ad20ee7f3238cf7b # {"$imagepolicy": "flux-system:seshat-api-latest"}  
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: metrics
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
