apiVersion: apps/v1
kind: Deployment
metadata:
  name: seshat-vdu-deployment
  namespace: default
  labels:
    app: seshat-vdu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: seshat-vdu
  template:
    metadata:
      labels:
        app: seshat-vdu
      annotations:
        k8s.v1.cni.cncf.io/networks: telco-data-plane
    spec:
      containers:
        - name: seshat-vdu
          # Note: Flux will automatically overwrite this placeholder tag with your real live AWS ECR image hash later! Total Bullshit!
          image: 468402787427.dkr.ecr.us-east-1.amazonaws.com/seshat_api:initial # {"$imagepolicy": "flux-system:seshat-api-latest"}  :${{ github.sha }}
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
