apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flux
  namespace: flux-system
  labels:
    app.kubernetes.io/part-of: flux
    app.kubernetes.io/component: monitoring  
    release: monitoring-monitoring
spec:
  namespaceSelector:
    matchNames:
      - flux-system
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - helm-controller
      - source-controller
      - kustomize-controller
      - image-automation-controller
      - image-reflector-controller
      - notification-controller
  podMetricsEndpoints:
    - targetPort: 9090
      path: /metrics
      interval: 30s
      scrapeTimeout: 25s
