apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: multus
  namespace: multus-system
  labels:
    release: monitoring-monitoring  # I hope this works
spec:
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - multus
      - seshat-vdu
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics