apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: multus
  namespace: default
  labels:
    release: monitoring-monitoring  # I hope this works
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: seshat-vdu
  podMetricsEndpoints:
    - port: metrics
      interval: 15s
      path: /metrics