apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: multus
  namespace: multus-system
  labels:
    release: monitoring-monitoring  # I hope this works
spec:
  selector:
    matchLabels:
      app: multus
  podMetricsEndpoints:
    - port: metrics
      path: /metrics