apiVersion: v1
kind: ServiceAccount
metadata:
  name: seshat-vdu-sa
  namespace: default    
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::468402787427:role/seshat_role_kube-system
   #://amazonaws.com: arn:aws:iam::468402787427:role/seshat_role