apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-storage-preparer
  namespace: kube-system             
spec:
  selector:
    matchLabels:
      name: node-storage-preparer
  template:
    metadata:
      labels:
        name: node-storage-preparer
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
      - name: create-mongodb-dir
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            echo "Checking and preparing host storage paths..."
            mkdir -p /host/mnt/data/mongodb
            chmod 777 /host/mnt/data/mongodb
            echo "Host directory prepared successfully."
        volumeMounts:
        - name: host-root
          mountPath: /host            
      containers:
      - name: pause-container
        image: registry.k8s.io/pause:3.9 
      volumes:
      - name: host-root
        hostPath:
          path: /                     # Points directly to the host machine root directory

