upf:
  enabled: false

webui:
  enabled: false

populate:
  enabled: true
  initCommands:
    - open5gs-dbctl add_ue_with_slice 999700000000001 465B5CE8B199B49FAA5F0A2EE238A6BC E8ED289DEBA952E4283B54E88E6183CA internet 1 111111

hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: true

sgwc:
  enabled: false

sgwu:
  enabled: false

amf:
  enabled: true
  config:
    plmnList:
      - plmn_id:
          mcc: "999"
          mnc: "70"
        s_nssai:
          - sst: 1
            sd: "111111"
      

ausf:
  enabled: true

bsf:
  enabled: true

nrf:
  enabled: true

nssf:
  enabled: true
  config:
    nsiList:
      - uri: http://open5gs-nrf-sbi:7777
        sst: 1
        sd: "111111"

pcf:
  enabled: true

scp:
  enabled: true

udm:
  enabled: true

udr:
  enabled: true

smf:
  enabled: true
  config:
    freeDiameter: false

mongodb:
  enabled: true
  persistence:
    enabled: true
    storageClass: "local-storage"
    size: 10Gi
    volumeName: "open5gs-mongodb-pv"
  image:
    registry: docker.io
    repository: bitnamilegacy/mongodb
    tag: 5.0.10-debian-11-r3