upf:
  enabled: false

webui:
  enabled: false

populate:
  enabled: false

hss:
  enabled: false

mme:
  enabled: false

pcrf:
  enabled: false

sgwc:
  enabled: false

sgwu:
  enabled: false

amf:
  enabled: true

ausf:
  enabled: true

bsf:
  enabled: true

nrf:
  enabled: true

nssf:
  enabled: true

pcf:
  enabled: true

scp:
  enabled: true

udm:
  enabled: true

udr:
  enabled: true

mongodb:
  enabled: true
  persistence:
    enabled: true
    storageClass: "local-storage"
    size: 10Gi
    volumeName: "open5gs-mongodb-pv"
  image:
    registry: docker.io
    repository: bitnamilegacy/mongodb
    tag: 5.0.10-debian-11-r3