name: "Application Delivery Pipeline"

on:
  push:
    branches:
      - main
  workflow_dispatch:   
jobs:
  build-and-ship:
    name: "Build & Ship Container"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  

    steps:
      
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Dump OIDC token claims  # Let us see
        shell: bash
        run: |
          echo "Requesting OIDC token..."

          TOKEN=$(curl -s \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=sts.amazonaws.com" | jq -r '.value')

             echo "Token received." 

             echo "$TOKEN" | cut -d '.' -f2 | base64 -d 2>/dev/null | jq .


      - name: Debug GitHub identity
        run: |
          echo "Role: ${{ vars.AWS_ROLE_TO_ASSUME }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"

      - name: Access AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          # FIX: Add this line so GitHub knows where to point the deployment.
          aws-region: us-east-1  

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

     
      - name: Build, Tag, and Push Mock vDU Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: seshat_api
          IMAGE_TAG: ${{ github.sha }} # Tags image with unique Git commit hash for tracking for potential debuggin issues I like this
        run: |
          cd apps

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

