name: "Application Delivery Pipeline"

on:
  push:
    branches:
      - main
  workflow_dispatch:
  # repository_dispatch:
  #   types:
  #    # - "flux-triggered" # Custom event type that Flux will trigger when it detects changes to the Git repository, allowing for a fully automated pipeline without manual intervention 
  #     - "Kustomization/seshat-app-delivery.flux-system" 
    
jobs:
  build-and-ship:
    name: "Build & Ship Container"
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read  # i hope this worksS

    steps:
      
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # - name: Authenticate with AWS
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}


       


      - name: Debug GitHub identity
        run: |
          echo "Role: ${{ vars.AWS_ROLE_TO_ASSUME }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "Workflow: ${{ github.workflow }}"

      - name: Access AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          # FIX: Add this line so GitHub knows where to point the deployment.
          aws-region: us-east-1  

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

     
      - name: Build, Tag, and Push Mock vDU Image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: seshat_api
          IMAGE_TAG: ${{ github.sha }} # Tags image with unique Git commit hash for tracking for potential debuggin issues I like this
        run: |
          cd apps

          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

